import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartDes - Smart Village",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="logo-container">
            <img 
              src="/images/logo.webp" 
              width="200" 
              height="40" 
              alt="SmartDes Logo" 
            />
          </div>

          <div className="header-right">
            <span className="header-title">SmartDes</span>
          </div>
        </header>

        {/* NAVBAR */}
        <nav className="bg-green-400 p-4 flex gap-4">
          <Link href="/">Home</Link>
          <Link href="/">Profil</Link>
          <Link href="/">Pelayanan</Link>
          <Link href="/">Potensi</Link>

        </nav>

        <main className="content">
          {children}
        </main>

        <footer>Copyright &copy; SMARTDES 2026</footer>
      </body>
    </html>
  );
}