import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartDes - Smart Village",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          {/* SISI KIRI: Logo */}
          <div className="logo-container">
            <img 
              src="/images/logo.webp" 
              width="200" 
              height="40" 
              alt="SmartDes Logo" 
            />
          </div>

          {/* SISI KANAN: Teks */}
          <div className="header-right">
            <span className="header-title">SmartDes</span>
          </div>
        </header>

        {/* Gunakan main untuk membungkus isi konten utama */}
        <main className="content">
          {children}
        </main>

        <footer>Copyright &copy; SMARTDES 2026</footer>
      </body>
    </html>
  );
}