import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SmartDes - Smart Village",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* membuat header  */}
        <header>
          <div className="header-right">
            <span className="header-title">SmartDes</span>
          </div>
        </header>

        <Navbar />

        <main className="content">
          {children}
        </main>
        {/* membuat footer */}
        <footer>Copyright &copy; SMARTDES 2026</footer>
      </body>
    </html>
  );
}